config/routes.rb
Rails.application.routes.draw do
  resources :students, except: %i[new create destroy]
  patch 'students/:id/advance', to: 'students#advance', as: 'advance_student'
  resources :teachers, only: %i[index show]

  root 'public#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  # A newly created student will start at lesson 1, part 1 (database defaults)

  belongs_to :teacher, optional: true # A student might not always have a teacher assigned to them

  validates :name, presence: true

  validates :lesson, numericality:
                       { greater_than_or_equal_to: 1,
                         less_than_or_equal_to: 100 }

  validates :lesson_part, numericality:
                       { greater_than_or_equal_to: 1,
                         less_than_or_equal_to: 3 }

  # Validate the lessons are only updated sequentially (if not using the advance method)
  validate :lesson_and_parts_update_sequentially, on: :update

  # Student is able to progress to the next lesson unless they have reached lesson 100, part 3
  def can_progress?
    lesson < 100 || lesson_part < 3
  end

  # Assign the student the next sequential lesson if able to do so
  def advance
    assign_attributes lesson: next_lesson, lesson_part: next_part if can_progress?
    self
  end

  # Assign the student to the next sequential lesson and commit to the database
  def advance!
    update! lesson: next_lesson, lesson_part: next_part if can_progress?
  end

  private

  # Pass validation only if the changed progress matches what the advance method would have returned
  def lesson_and_parts_update_sequentially
    advanced_progress = use_advance_on_unchanged_progress
    return if changed_progress_matches? advanced_progress
    errors.add :student, "can only progress to lesson #{advanced_progress['lesson']}, part #{advanced_progress['lesson_part']}"
  end

  # Returns the proper lesson progress using advance with progress from before the change
  def use_advance_on_unchanged_progress
    previous_student = dup
    previous_student.assign_attributes(lesson: lesson_was, lesson_part: lesson_part_was)
    previous_student.advance.attributes.slice('lesson', 'lesson_part')
  end

  # Check the students progress attributes against another progress hash
  def changed_progress_matches? advanced_progress
    student_progress = attributes.slice('lesson', 'lesson_part')
    student_progress == advanced_progress
  end

  # Increment the lesson if on part 3 of a lesson, unless at lesson 100
  def next_lesson
    lesson < 100 && lesson_part == 3 ? lesson + 1 : lesson
  end

  # Increment the lesson part unless on part 3
  def next_part
    lesson_part != 3 ? lesson_part + 1 : 1
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :students

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Rather than crash if a record isn't found, use the default 404 page instead
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  def render_404
    render file: "#{Rails.root}/public/404", status: :not_found, layout: false
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update advance]

  def index
    @students = Student.includes :teacher
  end

  def show
    render json: {
      student: {
        name: @student.name, progress: {
          lesson: @student.lesson, lesson_part: @student.lesson_part
        }
      }
    }
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to students_path, notice: "#{@student.name}'s progression was successfully updated."
    else
      render :edit
    end
  end

  def advance
    if @student.advance!
      redirect_to teacher_path(@student.teacher),
                  notice: "#{@student.name} has been advanced to lesson #{@student.lesson}, part #{@student.lesson_part}"
    else
      redirect_to teacher_path(@student.teacher),
                  alert: 'This student cannot advance further'
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:lesson, :lesson_part)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Convert an incoming flash type to a class name that bootstrap alert can understand
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LessonReporter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" id="nav-students">
                    <%= link_to 'Students', students_path, class: 'nav-link' %>
                </li>
                <li class="nav-item" id="nav-teachers">
                    <%= link_to 'Teachers', teachers_path, class: 'nav-link' %>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container" style="padding-top: 3em;">
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_lesson_progress.html.slim
.progress
  .progress-bar role='progressbar' style="width: #{33 * part}%" aria-valuenow="#{part * 30}" aria-valuemin='0' aria-valuemax='90' = "#{part}/3"

app/views/students/edit.html.slim
h1 Edit Student
br
hr

= form_for(@student) do |f|
  - if @student.errors.any?
    .alert.alert-danger role='alert'
      - @student.errors.full_messages.each do |message|
        li = message
  .form-group.row
    label.col-sm-2.col-form-label Name
    .col-sm-10
      p.form-control-static = @student.name
  .form-group.row
    label.col-sm-2.col-form-label Lesson
    .col-sm-10 = f.number_field :lesson, in: 1..100, class: 'form-control'
  .form-group.row
    label.col-sm-2.col-form-label Part
    .col-sm-10 = f.number_field :lesson_part, in: 1..3, class: 'form-control'
  = f.submit class: 'btn btn-primary btn-lg'

hr
= link_to 'Back', students_path, class: 'btn btn-info'

app/views/students/index.html.slim
h1.text-center Students
br
table.table.table-hover
  thead
    tr
      th #
      th Name
      th Lesson #
      th Progress in Lesson
      th Teacher
      th
  tbody
    - @students.each do |student|
      tr
        th scope='row' = student.id
        td = student.name
        td = student.lesson
        td = render 'shared/lesson_progress', part: student.lesson_part
        td = student.teacher&.name
        td
          => link_to 'JSON', student_path(student, format: :json), class: 'btn btn-success btn-sm'
          => link_to 'Edit', edit_student_path(student), class: 'btn btn-warning btn-sm'

app/views/teachers/index.html.slim
h1.text-center Teachers
br
table.table.table-hover
  thead
    tr
      th #
      th Name
      th Students
      th Furthest Lesson
      th
  tbody
    - @teachers.each do |teacher|
      tr
        th scope='row' = teacher.id
        td = teacher.name
        td = teacher.students&.count
        td = teacher.students&.maximum :lesson
        td = link_to 'Report', teacher_path(teacher), class: 'btn btn-success btn-sm'

app/views/teachers/show.html.slim
.text-center
  h1 Student Progress Report
  h4 = "Teacher: #{@teacher.name}"
  br
table.table.table-hover
  thead
    tr
      th #
      th Name
      th Lesson #
      th Progress in Lesson
      th
  tbody
    - @teacher.students.each do |student|
      tr
        th scope='row' = student.id
        td = student.name
        td = student.lesson
        td = render 'shared/lesson_progress', part: student.lesson_part
        td
          => link_to 'JSON', student_path(student, format: :json), class: 'btn btn-success btn-sm'
          = link_to 'Advance', advance_student_path(student), method: :patch, class: 'btn btn-primary btn-sm'